num1 = int(input("Digite o primeiro numero: "))
num2 = int(input("Digite o segundo numero: "))
print(f"\no Primeiro número é:", num1)
print(f"o Segundo número é:", num2)
soma = (num1+num2)
print(f"\nA soma dos numeros é:", soma)
